# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0004_oauth'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oauth',
            unique_together=set([('oauth_id', 'server')]),
        ),
    ]
