# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0009_auto_20171120_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileavatar',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProfileAvatar',
        ),
    ]
